# Generated by Django 4.2.14 on 2024-07-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('num_page', models.IntegerField(verbose_name='Num pages')),
                ('author', models.CharField(default='Abdulla Qodriy', max_length=30, verbose_name='Author')),
            ],
        ),
    ]
