# Generated by Django 4.2.14 on 2024-07-10 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='good book!', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, upload_to='books', verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(default="Poco's adventures", max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='book',
            name='num_page',
            field=models.IntegerField(default=121, verbose_name='Num pages'),
        ),
    ]
