# Generated by Django 5.0.7 on 2024-07-18 09:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_description_book_file_alter_book_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, upload_to='books', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'pdf'])], verbose_name='File'),
        ),
    ]
