# Generated by Django 4.2.14 on 2024-07-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Name')),
                ('img', models.ImageField(blank=True, upload_to='imgaes', verbose_name='Image')),
            ],
        ),
    ]
